Change `ParseState` to use a `Memory{T}` on Julia v1.11+
Julia v1.11 introduced the `Memory{T}` type, which is slowly but surely replacing some internal datastructures.  Without this change, precompiling `CSTParser.jl` fails with:

```
MethodError: Cannot `convert` an object of type
          Tokenize.Lexers.Lexer{Base.GenericIOBuffer{Memory{UInt8}},Tokenize.Tokens.RawToken} to an object of type
 
 Tokenize.Lexers.Lexer{Base.GenericIOBuffer{Vector{UInt8}},Tokenize.Tokens.RawToken}
  The function `convert` exists, but no method is defined for this combination of argument types.
```